
import { Box, Button, Link, Paper, Stack, styled, Typography } from "@mui/material"
import { useCookies } from "react-cookie";

const DisplayButton = styled(Button)(() => ({
    backgroundImage: 'linear-gradient(90deg, #20558A 0%, #650A67 100%)',
    backgroundColor: '#20558A',
    fontSize: '16px',
    color: 'white',
    width: '50%',
    flex: '1',
    '&:hover': {
        backgroundImage: 'linear-gradient(90deg, #12005A 0%, #12005A 100%)',
        backgroundColor: '#12005A',
    },
    '&[disabled]': {
        color: 'rgba(255, 255, 255, .8)',
    },
}));

const StyledBox = styled(Box)(({ theme }) => ({
    display: "flex",
}));

const StyledPaper = styled(Paper)(({ theme }) => ({
    padding: theme.spacing(4),
    position: 'relative',
    width: '100%',
    borderRadius: '6px',
    overflow: 'hidden'
}));

const StyledHeading = styled(Typography)(() =>
({
    color: '#40007B',
    fontWeight: 600
}))

export const DisclaimerPage = ({
}) => {
    const [cookies, setCookie] = useCookies(['DOCBOT']);
    return (
        <>
            <Box sx={{ width: '100%', padding: '2%', overflow:'auto' }}>
                <Box sx={{ borderBottom: 1, borderColor: 'divider', padding: 0 }}>
                    <StyledBox width='100%' id='styledcontainer'>
                        <StyledPaper variant={'elevation'} elevation={2} square>
                            <Stack>
                                <StyledHeading>
                                    About large language models
                                </StyledHeading>
                            </Stack>
                            <Stack>
                                The large language models behind these tools are pretrained on large sets of data. These models may respond with inaccurate, outdated, incomplete information. As a result, they are meant to be used as general knowledge bots and not search. The user is ultimately responsible for ensuring the accuracy, completeness, and relevance of any output generated by the tools.
                            </Stack>
                            <Stack style={{ paddingTop: '2%' }}>
                                <StyledHeading>
                                    Please note the following important points when using this tool:
                                </StyledHeading>
                            </Stack>
                            <Stack>
                                <ol type="1">
                                    <li>
                                        <b>Sensitive Data:</b> Protected Health Information (PHI), patient data, or sensitive Personally Identifiable information (PII) should not be entered into this tool.
                                    </li>
                                    <li>
                                        <b>Professional Advice:</b> The output from the NIAID GenAI tools should not be considered professional advice or a substitute for qualified experts in the relevant field. While the results can be impressive, it is essential to verify and cross-reference the information provided by the tool with reliable sources. The tool's responses may be inaccurate, outdated, incomplete, or not aligned with specific needs.
                                    </li>
                                    <li>
                                        <b>Limited Knowledge Base:</b> The tool is not intended to be an up-to-date knowledge base and GPT-4o is trained on information available prior to October 2023. If you require information dependent on data after the cutoff date, please be cautious as the tool may provide outdated information.
                                    </li>
                                </ol>
                            </Stack>
                            <Stack style={{ paddingBottom: '2%' }}>
                                <Typography>
                                    If you have questions about the above tools, NIAID GenAI Office Hours will be hosted every other Wednesday starting July 24th at 3pm ET <Link href="https://teams.microsoft.com/l/meetup-join/19%3ameeting_OWUzMTYyMjQtMjJiMS00MjlkLWFlMDktZjE3OTQxMTg2NThh%40thread.v2/0?context=%7b%22Tid%22%3a%2214b77578-9773-42d5-8507-251ca2dc2b06%22%2c%22Oid%22%3a%2252a696a3-e709-492c-b4b5-05a2b567fdf2%22%7d">here</Link> on MS Teams. You can also contact NIAID Help at <Link href="mailto:niaidithelp@niaid.nih.gov">niaidithelp@niaid.nih.gov</Link> or 1-866-740-3642.
                                </Typography>
                            </Stack>
                            <Stack style={{marginBottom:'1%', alignItems:'center'}}>
                                <Typography>
                                    Click "Accept" to proceed with using the application.
                                </Typography>
                            </Stack>
                            <Stack style={{ alignItems: 'center' }}>
                                <DisplayButton onClick={() => {
                                    setCookie("DOCBOT", "GENAI-DOCBOT", {
                                        maxAge: 7200
                                    });
                                }}>Accept</DisplayButton>
                            </Stack>
                        </StyledPaper>
                    </StyledBox>
                </Box>
            </Box>
        </>
    )
}